[package]
name = "gridwm"
version = "0.1.0"
edition = "2024"

[dependencies]
x11 = { version = "2.21.0", features = ["xlib", "xinerama"] }
log = "0.4.*"
simple_logger = "5.1.*"
configparser = "3.1.*"
