[package]
name = "gridwm"
version = "0.1.0"
edition = "2024"

[dependencies]
x11 = { version = "2.21", features = ["xlib", "xinerama"] }
log = "0.4"
simple_logger = "5.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
num-rational = "0.4"
num-traits = "0.2"
shell-words = "1.1"