[start]
exec = []

[general]
update_ms = 5

[window]
scale_steps = 20
window_bars = true
window_bar_height = 20

[keyboard]
layout = "de"

[mouse]
use_acceleration = false
use_acceleration_threshold = false
acceleration_value = 2.0
acceleration_threshold = 5

[desktop]
color = "#464646"

[bar]
text_color = "#ffffff"
background_color = "#000000"
height = 20
enable = true
update = 3.0
widgets = ["desktop", "time", "battery", "cpu", "mem"] # desktop, time, cpu, mem, battery

[keybinds]
gridwm = [
    ["SUPER+C", "close"],
    ["SUPER+RIGHT", "desktop_right"],
    ["SUPER+LEFT", "desktop_left"],
    ["ALT+Z", "unfloat"]
]
exec = [
    ["SUPER+ENTER", "konsole"],
    ["SUPER+SPACE", "rofi -show drun"]
]
move_mod = "ALT"
resize_mod = "ALT"