[start]
exec = []

[keyboard]
layout = "de"

[mouse]
use_acceleration = false
use_acceleration_threshold = false
acceleration_value = 2.0
acceleration_threshold = 5

[desktop]
color = "#464646"

[keybinds]
window = [
    ["CTRL+SHIFT+R", "close"],
    ["ALT+SHIFT+SPACE", "close"]
]