[start]
exec = []

[keyboard]
layout = "de"

[mouse]
use_acceleration = false
use_acceleration_threshold = false
acceleration_value = 2.0
acceleration_threshold = 5

[desktop]
color = "#464646"

[bar]
text_color = "#ffffff"
background_color = "#000000"
height = 20

[keybinds]
gridwm = [
    ["ALT+SUPER+C", "close"],
    ["SUPER+C", "close"],
    ["ALT+SUPER+RIGHT", "desktop_right"],
    ["ALT+SUPER+LEFT", "desktop_left"]
]
exec = [
    ["ALT+SUPER+ENTER", "konsole"],
    ["ALT+SUPER+SPACE", "rofi -show drun"]
]